replicaCount: 2

image:
  repository: ghcr.io/moel1001/document-service
  tag: "54217c1b9782cdc0dcbe3617582791e94dcf2116"
  pullPolicy: IfNotPresent

service:
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

serviceMonitor:
  enabled: true
  labels:
    release: monitoring

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
