replicaCount: 2

image:
  repository: ghcr.io/moel1001/document-service
  tag: "70fcca6abd22c62837ac1f947fd1ebcc3797b5fa"
  pullPolicy: IfNotPresent

service:
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
