replicaCount: 1

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health/ready
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls: []

serviceMonitor:
  enabled: true
  labels:
    release: monitoring-eks
