replicaCount: 2

image:
  repository: ghcr.io/moel1001/document-service
  tag: "ccde97250f8d95fb31c2e26c6ed917e98a4b11ba"
  pullPolicy: IfNotPresent

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
