apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.3
      helm:
        valueFiles:
          - $values/helm/platform-values/loki-values.yaml

    - repoURL: https://github.com/moel1001/internal-document-platform-.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true