{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: document-service
{{- with .Values.serviceMonitor.labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: document-service

  namespaceSelector:
    matchNames:
      - platform

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
