name: CI

# run when main is updated, or about to be updated by a PR
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  packages: write # write for packages to be able to push images to GHCR

jobs:
  build-and-push:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      # pull repo code into the VM
      - name: Checkout
        uses: actions/checkout@v4

      # install python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # install dependencies from requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # sanity check : python files compile
      - name: Basic check (compile)
        run: python -m compileall app

      # login to GHCR, Token automatically created for each worflow run
      - name: Log in to GHCR
        if: github.event_name == 'push'

        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build images using Dockerfile and push to GHCR
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/document-service:${{ github.sha }}


      - name: Update Helm values with new image tag
        if: github.event_name == 'push'
        run: |
          sed -i "s/^  tag: .*/  tag: \"${{ github.sha }}\"/" helm/document-service/values.yaml


          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add helm/document-service/values.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push
